# Generated by Django 3.2.7 on 2022-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220417_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='YoB',
            field=models.DateField(blank=True, null=True, verbose_name='Year of Birth (yyyy-mm-dd)'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('Bangladesh', 'Bangladesh'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('China', 'China'), ('France', 'France'), ('Germany', 'Germany'), ('India', 'India'), ('Italy', 'Italy'), ('Mexico', 'Mexico'), ('Pakistan', 'Pakistan'), ('Spain', 'Spain'), ('Tunisia', 'Tunisia'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[("Bachelor's", "Bachelor's"), ('Doctorate', 'Doctorate'), ("Master's", "Master's"), ('Secondary', 'Secondary')], max_length=30, null=True),
        ),
    ]
