# Generated by Django 3.2.7 on 2022-03-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_courseviewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='caption',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default='null', upload_to='video/%y'),
        ),
    ]
